# Generated by Django 3.1.2 on 2024-12-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scopes_tag_scopes_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopes',
            options={'ordering': ['-is_main', 'tag'], 'verbose_name': 'Видимость', 'verbose_name_plural': 'Видимость'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
