# Generated by Django 5.1.4 on 2024-12-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_auto_20241207_1745"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
        migrations.AddField(
            model_name="tag",
            name="articles",
            field=models.ManyToManyField(
                related_name="tags", through="articles.Scopes", to="articles.article"
            ),
        ),
        migrations.AlterField(
            model_name="scopes",
            name="is_main",
            field=models.BooleanField(),
        ),
    ]
